// <auto-generated />
namespace SimpleShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoverelationshipProductFeature_to_Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoverelationshipProductFeature_to_Product));
        
        string IMigrationMetadata.Id
        {
            get { return "202108130221199_Remove relationship ProductFeature_to_Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
