// <auto-generated />
namespace SimpleShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cascadedeleteproductfeature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascadedeleteproductfeature));
        
        string IMigrationMetadata.Id
        {
            get { return "202108140814263_Cascade delete product feature"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
